### ISSUE TITLE
Problem when menu drops down, it seems to slide underneath the main content

### ISSUE THREAD

**Issue by qt-tran** [shadeed/headers-css#3]
I tested on a few of your header designs, and it is the same issue when you click on the menu button. The nav__wrapper seems to slide underneath the main content.  I tried to  remove the z-index: -1 on the nav__wrapper, it seem to fix the problem, but now it slides over the site-header, and not underneath it. Here is a codepen link that demonstrate it  https://codepen.io/QTT/pen/wvgEoPW

**Comment by shadeed** [comment]
That's expected since I didn't add any `z-index` to the header element for abstraction purposes. Adding `z-index: 1` to the `.site-header` will solve the issue.

**Comment by Louboutin1017** [comment]
> That's expected since I didn't add any `z-index` to the header element for abstraction purposes. Adding `z-index: 1` to the `.site-header` will solve the issue.

Unfortunately, according to your fix, the error still persists.

kindly fix it thanks

**Comment by shadeed** [comment]
> > That's expected since I didn't add any `z-index` to the header element for abstraction purposes. Adding `z-index: 1` to the `.site-header` will solve the issue.
> 
> Unfortunately, according to your fix, the error still persists.
> 
> kindly fix it thanks

That is out the scope of this project.
