### ISSUE TITLE
Redundant display of menu 

### ISSUE THREAD

**Issue by itsdevansh** [shadeed/headers-css#4]
Hello Shadeed.
I am new to github so kindly excuse if I raise the issue in anomalous format.
 While exploring "Header 12" file I notices the there is a menu button as well as the list is displayed in the "sub_nav" class.
 
 This is persistent even when the window is resized. 

![image](https://user-images.githubusercontent.com/69133618/131210341-95d89eba-a3c0-4133-bc40-c5744cc17313.png)

![image](https://user-images.githubusercontent.com/69133618/131210352-4da942cf-2b4e-43ff-86d9-1b44a4de05d1.png)

Thank you.

**Comment by shadeed** [comment]
Hello, this design is intentional and I designed it with two menus in mind.
